# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BestFit(object):
    def setupUi(self, BestFit):
        BestFit.setObjectName("BestFit")
        BestFit.resize(800, 500)
        BestFit.setMinimumSize(QtCore.QSize(800, 500))
        BestFit.setMaximumSize(QtCore.QSize(800, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BestFit.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(BestFit)
        self.centralwidget.setObjectName("centralwidget")
        self.memoryAlloc = QtWidgets.QPushButton(self.centralwidget)
        self.memoryAlloc.setGeometry(QtCore.QRect(637, 420, 131, 41))
        self.memoryAlloc.setObjectName("memoryAlloc")
        self.randomCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.randomCheck.setGeometry(QtCore.QRect(350, 420, 141, 41))
        self.randomCheck.setObjectName("randomCheck")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 751, 391))
        self.tabWidget.setObjectName("tabWidget")
        self.processTab = QtWidgets.QWidget()
        self.processTab.setObjectName("processTab")
        self.tableMemory = QtWidgets.QTableView(self.processTab)
        self.tableMemory.setGeometry(QtCore.QRect(0, 0, 749, 355))
        self.tableMemory.setObjectName("tableMemory")
        self.tabWidget.addTab(self.processTab, "")
        self.memoryTab = QtWidgets.QWidget()
        self.memoryTab.setAccessibleName("")
        self.memoryTab.setObjectName("memoryTab")
        self.tableProcess = QtWidgets.QTableView(self.memoryTab)
        self.tableProcess.setGeometry(QtCore.QRect(0, 0, 749, 355))
        self.tableProcess.setObjectName("tableProcess")
        self.tabWidget.addTab(self.memoryTab, "")
        self.logTab = QtWidgets.QWidget()
        self.logTab.setObjectName("logTab")
        self.logView = QtWidgets.QTextEdit(self.logTab)
        self.logView.setEnabled(True)
        self.logView.setGeometry(QtCore.QRect(0, 0, 761, 361))
        self.logView.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.logView.setReadOnly(True)
        self.logView.setTabStopWidth(20)
        self.logView.setObjectName("logView")
        self.tabWidget.addTab(self.logTab, "")
        self.updateInfo = QtWidgets.QPushButton(self.centralwidget)
        self.updateInfo.setGeometry(QtCore.QRect(497, 420, 131, 41))
        self.updateInfo.setObjectName("updateInfo")
        BestFit.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BestFit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuAjudar = QtWidgets.QMenu(self.menubar)
        self.menuAjudar.setSeparatorsCollapsible(True)
        self.menuAjudar.setObjectName("menuAjudar")
        BestFit.setMenuBar(self.menubar)
        self.actionGithub = QtWidgets.QAction(BestFit)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGithub.setIcon(icon1)
        self.actionGithub.setIconVisibleInMenu(True)
        self.actionGithub.setObjectName("actionGithub")
        self.actionTeam = QtWidgets.QAction(BestFit)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTeam.setIcon(icon2)
        self.actionTeam.setIconVisibleInMenu(True)
        self.actionTeam.setObjectName("actionTeam")
        self.menuAjudar.addAction(self.actionGithub)
        self.menuAjudar.addAction(self.actionTeam)
        self.menubar.addAction(self.menuAjudar.menuAction())

        self.retranslateUi(BestFit)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BestFit)

    def retranslateUi(self, BestFit):
        _translate = QtCore.QCoreApplication.translate
        BestFit.setWindowTitle(_translate("BestFit", "Bestfit Memory Allocation Algorithm", None))
        self.memoryAlloc.setText(_translate("BestFit", "Memory Alloc", None))
        self.randomCheck.setText(_translate("BestFit", "Testing mode", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.processTab), _translate("BestFit", "Memory", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.memoryTab), _translate("BestFit", "Processes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logTab), _translate("BestFit", "Logs", None))
        self.updateInfo.setText(_translate("BestFit", "Update", None))
        self.menuAjudar.setTitle(_translate("BestFit", "More", None))
        self.actionGithub.setText(_translate("BestFit", "Github", None))
        self.actionTeam.setText(_translate("BestFit", "About", None))


